name: deploy to s3 developMode
on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    if: github.head_ref == 'devfrontend'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.19.0

      - name: Install dependencies
        working-directory: frontend
        run: npm install

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Sync files to S3 bucket
        run: |
          aws s3 sync frontend/dist s3://passwordsaver-frontend-bucket --delete
